# Generated by Django 5.2.12 on 2026-03-30 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria_total',
            field=models.IntegerField(verbose_name='Carga Horária Total'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracao_meses',
            field=models.IntegerField(verbose_name='Duração Meses'),
        ),
        migrations.AlterField(
            model_name='cursodisciplina',
            name='carga_horaria',
            field=models.IntegerField(verbose_name='Carga Horária'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='numero_faltas',
            field=models.IntegerField(verbose_name='Número de Faltas'),
        ),
        migrations.AlterField(
            model_name='instituicaoensino',
            name='telefone',
            field=models.IntegerField(verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='ocupacao',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Ocupação'),
        ),
    ]
