# Generated by Django 5.2.12 on 2026-04-06 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_disciplina_areasaber_alter_disciplina_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma'),
        ),
    ]
