# Generated by Django 5.2.12 on 2026-04-06 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_matricula_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='turma',
        ),
        migrations.AddField(
            model_name='turma',
            name='matricula',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.matricula', verbose_name='Turma'),
        ),
    ]
