# Generated by Django 5.2.12 on 2026-04-06 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_matricula_turma_turma_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='matricula',
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso'),
        ),
    ]
