# Generated by Django 5.2.12 on 2026-04-06 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_turma_matricula_matricula_turma_turma_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, verbose_name='Sigla Da Unidade Federativa')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome Da Unidade Federativa')),
            ],
            options={
                'verbose_name': 'UF',
                'verbose_name_plural': 'UFs',
            },
        ),
        migrations.AlterField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.uf', verbose_name='UF'),
        ),
    ]
