# Generated by Django 5.2.12 on 2026-04-06 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_uf_alter_cidade_uf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursodisciplina',
            options={'verbose_name': 'Curso Disciplina', 'verbose_name_plural': 'Cursos Disciplinas'},
        ),
    ]
