# Generated by Django 5.2.12 on 2026-04-06 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_cursodisciplina_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='turma',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='turma',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='turma',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso'),
        ),
    ]
