# Generated by Django 5.2.12 on 2026-04-06 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_avaliacao_turma_disciplina_turma_frequencia_turma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.uf', verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso'),
        ),
    ]
