# Generated by Django 5.2.12 on 2026-04-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_avaliacao_turma_alter_cidade_uf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicaoensino',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
